---

name: 'Setup Django backend'
description: 'Set up prerequisites for a Maykin Django backend'

inputs:
  apt-packages:
    description: Any apt packages to install, space-separated
    required: false
    default: 'gettext postgresql-client'

  python-version:
    description: Python version, passed to actions/setup-python
    required: true
    default: '3.10'

  optimize-postgres:
    description: >
      Tune postgres for non-durable but faster tests. Requires 'pg-service' name. Set
      to string 'yes' to enable (the default).
    required: false
    default: 'yes'

  pg-service:
    description: >
      Name of the postgres service. If not specified (the default), no optimization is
      done. See 'optimize-postgres'.
    required: false
    default: ''

  setup-node:
    description: Whether to setup node and npm packages.
    required: false
    default: 'yes'

  nvmrc-custom-dir:
    description: Directory within the github.workspace directory where to find the .nvmrc file (for the setup-node action).
    required: false
    default: ''

  npm-ci-flags:
    description: Additional arguments for the 'npm ci' command.
    required: false
    default: ''

  working-directory:
    description: Specifies the working directory where commands are run.
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Install OS dependencies
      if: ${{ inputs.apt-packages }}
      run: |
        sudo apt-get update
        sudo apt-get install --yes ${{ inputs.apt-packages }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Tune PostgreSQL for test performance
      if: ${{ inputs.pg-service != '' && inputs.optimize-postgres == 'yes' }}
      run: |
        docker exec -i ${{ inputs.pg-service }} bash << EOF
          sed -i -e 's/#fsync = on/fsync = off/' /var/lib/postgresql/data/postgresql.conf
          sed -i -e 's/#full_page_writes = on/full_page_writes = off/' /var/lib/postgresql/data/postgresql.conf
          sed -i -e 's/#synchronous_commit = on/synchronous_commit = off/' /var/lib/postgresql/data/postgresql.conf
          sed -i -e 's/shared_buffers = 128MB/shared_buffers = 2GB/' /var/lib/postgresql/data/postgresql.conf
          sed -i -e 's/max_wal_size = 1GB/max_wal_size = 4GB/' /var/lib/postgresql/data/postgresql.conf
        EOF

        docker restart --time=0 ${{ inputs.pg-service }}

        # block until container is up and running again
        until pg_isready -h 127.0.0.1; do
          echo "Waiting for DB to be up again..."
          sleep 1
        done

        echo "Done configuring PostgreSQL for faster tests."
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
      id: setup-uv
      with:
        python-version: ${{ inputs.python-version }}
        # Disable cashing on the default branch and tag builds
        enable-cache: "${{ !(github.ref_name == github.event.repository.default_branch || startsWith(github.ref, 'refs/tags/')) }}"
        activate-environment: 'true'
        venv-path: '../.venv'
        prune-cache: 'false'
        cache-dependency-glob: |
          **/requirements/*.txt
          **/requirements/*.in
          **/*requirements*.txt
          **/*requirements*.in
          **/*constraints*.txt
          **/*constraints*.in
          **/pyproject.toml
          **/uv.lock
          **/*.py.lock

    - name: Install backend dependencies
      run: |
        uv pip install \
          -r requirements/ci.txt
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      if: ${{ inputs.setup-node == 'yes' }}
      with:
        package-manager-cache: 'false'
        node-version-file: ${{ inputs.nvmrc-custom-dir && format('{0}/{1}', inputs.nvmrc-custom-dir, '.nvmrc') || '.nvmrc' }}

    - name: Build frontend
      if: ${{ inputs.setup-node == 'yes' }}
      run: |
        npm ci ${{ inputs.npm-ci-flags }}
        npm run build
      shell: bash
      working-directory: ${{ inputs.working-directory }}
